let codes = {
    "a": "KeyA",
    "b": "KeyB",
    "c": "KeyC",
    "d": "KeyD",
    "e": "KeyE",
    "f": "KeyF",
    "g": "KeyG",
    "h": "KeyH",
    "i": "KeyI",
    "j": "KeyJ",
    "k": "KeyK",
    "l": "KeyL",
    "m": "KeyM",
    "n": "KeyN",
    "o": "KeyO",
    "p": "KeyP",
    "q": "KeyQ",
    "r": "KeyR",
    "s": "KeyS",
    "t": "KeyT",
    "u": "KeyU",
    "v": "KeyV",
    "w": "KeyW",
    "x": "KeyX",
    "y": "KeyY",
    "z": "KeyZ",
    "1": "Digit1",
    "2": "Digit2",
    "3": "Digit3",
    "4": "Digit4",
    "5": "Digit5",
    "6": "Digit6",
    "7": "Digit7",
    "8": "Digit8",
    "9": "Digit9",
    "0": "Digit0",
    "`": "Backquote",
    "-": "Minus",
    "=": "Equal",
    "Backspace": "Backspace",
    "Tab": "Tab",
    "[": "BracketLeft",
    "]": "BracketRight",
    "\\": "Backslash",
    ";": "Semicolon",
    "'": "Quote",
    "Enter": "Enter",
    "Shift": "ShiftLeft",
    ",": "Comma",
    ".": "Period",
    "/": "Slash",
    "Shift": "ShiftRight",
    "Control": "ControlLeft",
    "Alt": "AltLeft",
    "Meta": "MetaLeft",
    " ": "Space",
    "Meta": "MetaRight",
    "Alt": "AltRight",
    "ArrowLeft": "ArrowLeft",
    "ArrowUp": "ArrowUp",
    "ArrowDown": "ArrowDown",
    "ArrowRight": "ArrowRight",
    "CapsLock": "CapsLock",
    "A": "KeyA",
    "B": "KeyB",
    "C": "KeyC",
    "D": "KeyD",
    "E": "KeyE",
    "F": "KeyF",
    "G": "KeyG",
    "H": "KeyH",
    "I": "KeyI",
    "J": "KeyJ",
    "K": "KeyK",
    "L": "KeyL",
    "M": "KeyM",
    "N": "KeyN",
    "O": "KeyO",
    "P": "KeyP",
    "Q": "KeyQ",
    "R": "KeyR",
    "S": "KeyS",
    "T": "KeyT",
    "U": "KeyU",
    "V": "KeyV",
    "W": "KeyW",
    "X": "KeyX",
    "Y": "KeyY",
    "Z": "KeyZ",
    "~": "Backquote",
    "!": "Digit1",
    "@": "Digit2",
    "#": "Digit3",
    "$": "Digit4",
    "%": "Digit5",
    "^": "Digit6",
    "&": "Digit7",
    "*": "Digit8",
    "(": "Digit9",
    ")": "Digit0",
    "_": "Minus",
    "+": "Equal",
    "{": "BracketLeft",
    "}": "BracketRight",
    "|": "Backslash",
    ":": "Semicolon",
    "\"": "Quote",
    "<": "Comma",
    ">": "Period",
    "?": "Slash"
};

let keys = {
    "KeyA": "a",
    "KeyB": "b",
    "KeyC": "c",
    "KeyD": "d",
    "KeyE": "e",
    "KeyF": "f",
    "KeyG": "g",
    "KeyH": "h",
    "KeyI": "i",
    "KeyJ": "j",
    "KeyK": "k",
    "KeyL": "l",
    "KeyM": "m",
    "KeyN": "n",
    "KeyO": "o",
    "KeyP": "p",
    "KeyQ": "q",
    "KeyR": "r",
    "KeyS": "s",
    "KeyT": "t",
    "KeyU": "u",
    "KeyV": "v",
    "KeyW": "w",
    "KeyX": "x",
    "KeyY": "y",
    "KeyZ": "z",
    "Digit1": "1",
    "Digit2": "2",
    "Digit3": "3",
    "Digit4": "4",
    "Digit5": "5",
    "Digit6": "6",
    "Digit7": "7",
    "Digit8": "8",
    "Digit9": "9",
    "Digit0": "0",
    "Backquote": "`",
    "Minus": "-",
    "Equal": "=",
    "Backspace": "Backspace",
    "Tab": "Tab",
    "BracketLeft": "[",
    "BracketRight": "]",
    "Backslash": "\\",
    "Semicolon": ";",
    "Quote": "'",
    "Enter": "Enter",
    "ShiftLeft": "Shift",
    "Comma": ",",
    "Period": ".",
    "Slash": "/",
    "ShiftRight": "Shift",
    "ControlLeft": "Control",
    "AltLeft": "Alt",
    "MetaLeft": "Meta",
    "Space": " ",
    "MetaRight": "Meta",
    "AltRight": "Alt",
    "ArrowLeft": "ArrowLeft",
    "ArrowUp": "ArrowUp",
    "ArrowDown": "ArrowDown",
    "ArrowRight": "ArrowRight",
    "KeyA": "A",
    "KeyB": "B",
    "KeyC": "C",
    "KeyD": "D",
    "KeyE": "E",
    "KeyF": "F",
    "KeyG": "G",
    "KeyH": "H",
    "KeyI": "I",
    "KeyJ": "J",
    "KeyK": "K",
    "KeyL": "L",
    "KeyM": "M",
    "KeyN": "N",
    "KeyO": "O",
    "KeyP": "P",
    "KeyQ": "Q",
    "KeyR": "R",
    "KeyS": "S",
    "KeyT": "T",
    "KeyU": "U",
    "KeyV": "V",
    "KeyW": "W",
    "KeyX": "X",
    "KeyY": "Y",
    "KeyZ": "Z",
    "Backquote": "~",
    "Digit1": "!",
    "Digit2": "@",
    "Digit3": "#",
    "Digit4": "$",
    "Digit5": "%",
    "Digit6": "^",
    "Digit7": "&",
    "Digit8": "*",
    "Digit9": "(",
    "Digit0": ")",
    "Minus": "_",
    "Equal": "+",
    "ShiftLeft": "Shift",
    "BracketLeft": "{",
    "BracketRight": "}",
    "Backslash": "|",
    "Semicolon": ":",
    "Quote": "\"",
    "Comma": "<",
    "Period": ">",
    "Slash": "?",
};

class KeyBoard {
    constructor () {
        this.down = {};

        document.addEventListener('keydown', (e)=> {
            this.down[e.code] = true;
        });
        document.addEventListener('keyup', (e)=> {
            this.down[e.code] = false;
        });
    }

    isDown (code) {
        return code in this.down && this.down[code];
    }

    isUp (code) {
        return !this.isDown(code);
    }
};
KeyBoard.codes = codes;
KeyBoard.keys = keys;

module.exports = KeyBoard;